### ISSUE TITLE
Wrong License in README.md

### ISSUE THREAD

**Issue by bdekany** [lgmorand/aca-vs-aks#8]
There is a License conflict 🙀 

* README.md link to [Apache v2](https://choosealicense.com/licenses/apache-2.0/)
* LICENSE file in repo is [MPLv2](https://choosealicense.com/licenses/mpl-2.0/)

But MPLv2 don't allow this: 1.5. "Incompatible With Secondary Licenses"

**Comment by lgmorand** [comment]
oui je sais pas pourquoi j'ai mixé

**Comment by lgmorand** [comment]
@bdekany la prochaine fois, mets direct ton nom dans les contribs :)

**Comment by bdekany** [comment]
Non, je suis la formation "Product Manager: How to make devs do the hard work for you" sur Edx.org
